# Generated by Django 4.1.3 on 2022-12-21 09:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Rhymes",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user", models.CharField(max_length=250)),
                ("word", models.CharField(max_length=250)),
                (
                    "date",
                    models.CharField(
                        default=datetime.date(2022, 12, 21), max_length=250
                    ),
                ),
                (
                    "is_accepted",
                    models.BooleanField(default=False, verbose_name="Accepted"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="WordOfTheDay",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.CharField(max_length=250)),
                ("Word_of_the_day", models.CharField(default="", max_length=250)),
            ],
        ),
    ]
