# Generated by Django 4.1.3 on 2023-01-11 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0003_delete_wordoftheday_rhymes_word_of_the_day_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="WordOfTheDay",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.CharField(max_length=250)),
                ("Word_of_the_day", models.CharField(default="", max_length=250)),
            ],
        ),
        migrations.RemoveField(
            model_name="rhymes",
            name="word_of_the_day",
        ),
    ]
