# Generated by Django 4.1.3 on 2023-01-11 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0004_wordoftheday_remove_rhymes_word_of_the_day"),
    ]

    operations = [
        migrations.AddField(
            model_name="rhymes",
            name="word_of_the_day",
            field=models.CharField(default="", max_length=250),
        ),
    ]
