# Generated by Django 4.1.3 on 2023-01-23 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0006_remove_rhymes_is_accepted_alter_rhymes_date"),
    ]

    operations = [
        migrations.CreateModel(
            name="Accepted",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user", models.CharField(max_length=250)),
                ("word", models.CharField(max_length=250)),
                ("Word_of_the_day", models.CharField(default="", max_length=250)),
                ("count", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Rejected",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user", models.CharField(max_length=250)),
                ("word", models.CharField(max_length=250)),
                ("Word_of_the_day", models.CharField(default="", max_length=250)),
                ("count", models.IntegerField()),
            ],
        ),
    ]
