# Generated by Django 4.1.3 on 2023-01-24 08:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0007_accepted_rejected"),
    ]

    operations = [
        migrations.AddField(
            model_name="rhymes",
            name="is_accepted",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="rhymes",
            name="date",
            field=models.CharField(default=datetime.date(2023, 1, 24), max_length=250),
        ),
    ]
