# Generated by Django 4.1.3 on 2023-01-25 12:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0008_rhymes_is_accepted_alter_rhymes_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="accepted",
            name="date",
            field=models.CharField(default=datetime.date(2023, 1, 25), max_length=250),
        ),
        migrations.AddField(
            model_name="accepted",
            name="is_accepted",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="rejected",
            name="date",
            field=models.CharField(default=datetime.date(2023, 1, 25), max_length=250),
        ),
        migrations.AddField(
            model_name="rejected",
            name="is_accepted",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="accepted",
            name="count",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="rejected",
            name="count",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="rhymes",
            name="date",
            field=models.CharField(default=datetime.date(2023, 1, 25), max_length=250),
        ),
    ]
