# Generated by Django 4.1.3 on 2023-01-27 12:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0009_accepted_date_accepted_is_accepted_rejected_date_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="accepted",
            old_name="Word_of_the_day",
            new_name="word_of_the_day",
        ),
        migrations.RenameField(
            model_name="rejected",
            old_name="Word_of_the_day",
            new_name="word_of_the_day",
        ),
        migrations.RenameField(
            model_name="wordoftheday",
            old_name="Word_of_the_day",
            new_name="word_of_the_day",
        ),
        migrations.AlterField(
            model_name="accepted",
            name="date",
            field=models.CharField(default=datetime.date(2023, 1, 27), max_length=250),
        ),
        migrations.AlterField(
            model_name="rejected",
            name="date",
            field=models.CharField(default=datetime.date(2023, 1, 27), max_length=250),
        ),
        migrations.AlterField(
            model_name="rhymes",
            name="date",
            field=models.CharField(default=datetime.date(2023, 1, 27), max_length=250),
        ),
    ]
