# Generated by Django 4.1.3 on 2023-01-27 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0010_rename_word_of_the_day_accepted_word_of_the_day_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="accepted",
            old_name="word_of_the_day",
            new_name="Word_of_the_day",
        ),
        migrations.RenameField(
            model_name="rejected",
            old_name="word_of_the_day",
            new_name="Word_of_the_day",
        ),
        migrations.RenameField(
            model_name="wordoftheday",
            old_name="word_of_the_day",
            new_name="Word_of_the_day",
        ),
    ]
