# Generated by Django 4.1.3 on 2023-01-30 07:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0011_rename_word_of_the_day_accepted_word_of_the_day_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="rhymes",
            old_name="word_of_the_day",
            new_name="Word_of_the_day",
        ),
        migrations.AlterField(
            model_name="accepted",
            name="date",
            field=models.CharField(default=datetime.date(2023, 1, 30), max_length=250),
        ),
        migrations.AlterField(
            model_name="rejected",
            name="date",
            field=models.CharField(default=datetime.date(2023, 1, 30), max_length=250),
        ),
        migrations.AlterField(
            model_name="rhymes",
            name="date",
            field=models.CharField(default=datetime.date(2023, 1, 30), max_length=250),
        ),
    ]
