# Generated by Django 4.1.4 on 2023-03-02 15:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0013_alter_accepted_date_alter_rejected_date_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="RandomWords",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ref_id", models.IntegerField()),
                ("user", models.CharField(max_length=250)),
                ("word", models.CharField(max_length=250)),
                (
                    "date",
                    models.CharField(default=datetime.date(2023, 3, 2), max_length=250),
                ),
                ("is_accepted", models.BooleanField(default=False)),
                ("count", models.IntegerField(default=0)),
            ],
        ),
        migrations.AlterField(
            model_name="accepted",
            name="date",
            field=models.CharField(default=datetime.date(2023, 3, 2), max_length=250),
        ),
        migrations.AlterField(
            model_name="rejected",
            name="date",
            field=models.CharField(default=datetime.date(2023, 3, 2), max_length=250),
        ),
        migrations.AlterField(
            model_name="rhymes",
            name="date",
            field=models.CharField(default=datetime.date(2023, 3, 2), max_length=250),
        ),
    ]
